version: '1.0'
mode: remote
identifier: CrowAks
category: Production
username: devopsbot
jobs:
- name: CROW CLI DEPLOYMENT
  stages:
  - name: K8s | Update image & Scale
    tasks:
      kubernetes:
        enabled: true
        kubeconfig_path: /home/devopsbot/.kube/config
        namespace: tenant-dob-985968
        dry_run: false
        verbose: false
        steps:
        - action: set_image
          kind: deployment
          name: dob-985968-cli
          container: dob-985968-cli
          image: devopsbot.azurecr.io/crow-cli:V0.1.34
        - action: rollout_status
          kind: deployment
          name: dob-985968-cli
          timeout: 240s
